function [fitresult, gof] = createLinFit(X, Y, Z)
%CREATEFIT(X,Y,U)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : X
%      Y Input : Y
%      Z Output: Z
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Jul-2014 10:54:48


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( X, Y, Z );
% [xData, yData, zData] = prepareSurfaceData_nowarning( X, Y, Z );

% Set up fittype and options.
ft = 'linearinterp';
opts = fitoptions( ft );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, [xData, yData], zData );
% legend( h, 'untitled fit 1', 'U vs. X, Y', 'Location', 'NorthEast' );
% % Label axes
% xlabel( 'X' );
% ylabel( 'Y' );
% zlabel( 'U' );
% grid on
% view( -127.5, 90 );


